# Основные понятия Python

## Условные выражения (IF...ELSE, IF...ELIF)

*Конструкиця IF...ELSE*

- `if (expression):
    (code_area1)
   else:
    (code_area2)`
    
*Конструкиця IF...ELIF*

- `if (expression1):
    (code_area1)
   elif (expression2):
    (code_area2)`
    

### Задание 1.1.1

(**1 балл**) Написать программу, которая будет выводить:
- "Неудовлетворительно", нсли студент набрал от 0-39 баллов
- "Удовлетворительно", если студент набрал от 40-59 баллов
- "Хорошо", если студент набрал от 60-79
- "Отлично", если студент набрал от 80-100

In [15]:
#Решение задания 1.1.1#

try:
    score = int(input("Введите количество баллов: "))
    print("Score: ", score)

    if (-1 < score <= 39):
        print("Неудовлетворительно")

    elif (39 < score <= 59):
        print("Удовлетворительно")

    elif (59 < score <= 79):
        print("Хорошо")

    elif (79 < score <= 100):
        print("Отлично")

    else:
        print("Введено значение вне диапазона 0-100")

except ValueError:
	  print('Требуется целое число.')



Введите количество баллов: 67
Score:  67
Хорошо


**+1 балл**

Что можно сделать лучше:


* с большой буквы пишутся в python обычно только названия классов, поэтому лучше Score заменить на score
* хотелось бы иметь возможность вводить score с клавиатуры, а не выбирать случайно: `score = int(input("Введите количество баллов: "))`
* можно вместо условия `(x < score and score <= y)` писать просто `x < score <= y`




## Функции

*Функции должны делать одну вещь и делать ее хорошо и делать только ее.  © Роберт С. Мартин*

`def имя_функции(параметры):
     определение функции`
     




    
    
    

### Задание 1.1.2

(**1 балл**) Напишите программу с двумя функциями. Первая функция должна принимать в качестве параметра целое число и возвращать результат умножения этого числа на 2. Вторая функция должна принимать в качестве параметра целое число и возвращать результат деления этого числа на 4. Вызовите первую функцию, сохраните результат в пременной и передайте ее в качестве параметра во вторую функцию.


In [16]:
#Решение задания 1.1.2#
def multiply_by_2(a):
    return a * 2

def divide_by_4(a):
    return a / 4.0

try:
    a = int(input("Введите целое число: ")) #Произвольное число
    a = multiply_by_2(a)
    a = divide_by_4(a)
    print("Результат:", a)

except ValueError:
	  print('Требуется целое число.')

except NameError:
	  print('Переменные не были определены.')

Введите целое число: -1
Результат: -0.5


**+1 балл**

Что можно сделать лучше:


* с большой буквы и через camel-style пишутся в python обычно только названия классов, поэтому лучше `FirstFunction` заменить на `first_function`
* названия функции должна отражать то, что функция делает, поэтому лучше было бы назвать `multiply_by_2` и `divide_by_4`

# Библиотека NumPy

**NumPy** (от Numerical Python - "числовой Python") - библиотека, предназначенная для работы с числовыми массивами, как одномерными, так и многомерными. Массивы библиотеки NumPy похожи на встроенный тип данных Python list, но обеспечивает гораздо более эффективное хранение и операциис данными при росте размера массивов.

In [ ]:
#импорт библиотеки

import numpy as np

Дан двумерный массив:

In [ ]:
x = np.array([[12, 5, 0, 3],
              [11, 3, 7, 9],
              [3, 5, 2, 4]])

x

array([[12,  5,  0,  3],
       [11,  3,  7,  9],
       [ 3,  5,  2,  4]])

## Задание 1.2.1

(**2 балла**) С использованием функции библиотеки NumPy посчитать:
- сколько элементов меньше 8 в данном массиве
- сколько элементов меньше 6 в каждой строке массива
- сколько элементов больше 4 в каждом столбце

In [38]:
#Решение#
import numpy as np


x = np.array([[12, 5, 0, 3],
              [11, 3, 7, 9],
              [3, 5, 2, 4]])

print("Under 8: ", np.sum(x < 8))
print("Under 6, each row: ", np.sum(x < 6, axis=1))
print("Above 4, each column: ", np.sum(x > 4, axis=0))


Under 8:  9
Under 6, each row:  [3 1 4]
Above 4, each column:  [2 2 1 1]


**Что точно стоит улучшить:**

В numpy практически все действия можно делать без циклов. Это будет и очень быстро работать и легко читаться

Например, чтобы посчитать количество элементов меньше 8, мы можем сначала сделать так:

In [ ]:
# получим матрицу, где каждый элемент - это булевое значение. True, если данный элемент < 8 и False в противном случае
x < 8

array([[False,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [ ]:
# теперь нам достаточно просто посчитать количество элементов, которые имеют значение True
# мы можем это сделать простым np.sum(), т.к. при суммировании True превращается в 1, а False в 0:
np.sum(x < 8)

9

Практически все функции в np имеют параметр axis (ось), который используется для работы с определенной осью (axis=0 отвечает за "направление" строк, а axis=1 за "направление" столбцов). Например, в данном задании, если мы хотим посчитать, сколько элементов меньше 6 в каждой строке массива, мы можем сделать так:

In [ ]:
# т.к. хотим суммировать по "направлению" столбцов и таким образом для каждой строки получаем сумму по всем столбцам:
np.sum(x < 6, axis=1)

array([3, 1, 4])

In [ ]:
# нужно будет доделать последнее задание самостоятельно

С использованием функции библиотеки NumPy выяснить:
- имеются ли в массиве какие-либо значения, превышающие 13
- все ли значения в каждой строке кратны двум

In [31]:
#Решение#
import numpy as np


x = np.array([[12, 5, 0, 3],
              [11, 3, 7, 9],
              [3, 5, 2, 4]])

print("Any above 13: ", np.any(x > 13))
print("All elements even in a row: ", np.all(x % 2 == 0, axis=1))



Any above 13:  False
All elements even in a row:  [False False False]


**Что улучшить:**

В первом задании можно использовать ту же идею с `x > 13`, а затем использовать `np.any`

Во втором аналогично, но уже использовать `np.all` с указанием нужной `axis`


Создать еще один **рандомный** массив, объединить его с уже имеющимся и с помощью функций NumPy найти максимальный элемент в каждой строке.

In [40]:
#Решение#
import numpy as np


x = np.array([[12, 5, 0, 3],
              [11, 3, 7, 9],
              [3, 5, 2, 4]])

x = np.concatenate([x, np.random.randint(0, 15, (3, 4))], axis=1)

print(x, "\n")
print(x.max(axis=1))


[[12  5  0  3  0  3  5  8]
 [11  3  7  9  3  0 14 13]
 [ 3  5  2  4 14  7  0  4]] 

[12 14 14]


Лучше будет переписать без цикла

**+1 балл**

Очень рекомендую переписать задание с теми замечаниями, что я оставил. Если всё поправите, то поставлю недостающий балл

# Библиотека Pandas

**Pandas** - библиотека на языке Python для обработки и анализа данных. Pandas является надстройкой над библиотекой NumPy, обеспечивающей эффективную реализацию класса DataFrame. Объекты **DataFrame** - многомерные массивы с метками для строк и столбцов, а также зачастую с неоднородным типом данных и/или пропущенными данными.

In [ ]:
#импорт библиотеки

import pandas as pd

In [ ]:
path = "titanic.csv"
dataset = pd.read_csv(path)

dataset

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

## Задание 1.3.1

(**2 балла**)
1. Вывести все записи, содержащие данные о пассажирах женского пола и в возрасте старше 20 лет

In [43]:
#Решение#
import pandas as pd

path = "titanic.csv"
dataset = pd.read_csv(path)

dataset[(dataset['Sex'] == 'female') & (dataset['Age'] > 20)]


Survived  Pclass                                               Name  \
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
8           1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson   
11          1       1                            Miss. Elizabeth Bonnell   
..        ...     ...                                                ...   
870         1       2               Mrs. Samuel (Hannah Wizosky) Abelson   
875         1       1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter   
876         1       2        Mrs. William (Imanita Parrish Hall) Shelley   
878         0       3                        Miss. Gerda Ulrika Dahlberg   
881         0       3                Mrs. William (Margaret Norton) Rice   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
8    female  27.0                        0                        2  11.1333  
11   female  58.0                        0                        0  26.5500  
..      ...   ...                      ...                      ...      ...  
870  female  28.0                        1                        0  24.0000  
875  female  56.0                        0                        1  83.1583  
876  female  25.0                        0                        1  26.0000  
878  female  22.0                        0                        0  10.5167  
881  female  39.0                        0                        5  29.1250  

[222 rows x 8 columns]

2. Вывести дубликаты по возрасту и классу и отсортировать по этим же значениям по убыванию

In [44]:
#Решение#
import pandas as pd

path = "titanic.csv"
dataset = pd.read_csv(path)

dataset[dataset.duplicated(['Pclass', 'Age'])].sort_values(['Pclass', 'Age'], ascending = False)


Survived  Pclass                                              Name  \
404         0       3                   Mr. Carl/Charles Peter Widegren   
628         0       3                        Mr. Johan Svensson Lundahl   
664         0       3                         Mr. Knud Paust Rommetvedt   
767         0       3                            Mr. Niels Peder Jensen   
589         0       3                         Mr. William James Elsbury   
..        ...     ...                                               ...   
697         1       1  Mrs. John Jacob (Madeleine Talmadge Force) Astor   
547         1       1                        Mr. John Borland Jr Thayer   
777         1       1          Mrs. Albert Adrian (Vera Gillespie) Dick   
501         1       1                              Miss. Roberta Maioni   
849         1       1                          Miss. Mary Conover Lines   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard      Fare  
404    male  51.0                        0                        0    7.7500  
628    male  51.0                        0                        0    7.0542  
664    male  49.0                        0                        0    7.7750  
767    male  48.0                        0                        0    7.8542  
589    male  47.0                        0                        0    7.2500  
..      ...   ...                      ...                      ...       ...  
697  female  18.0                        1                        0  227.5250  
547    male  17.0                        0                        2  110.8833  
777  female  17.0                        1                        0   57.0000  
501  female  16.0                        0                        0   86.5000  
849  female  16.0                        0                        1   39.4000  

[699 rows x 8 columns]

3. Используя группировку:
- посчитать сколько пассажиров в каждом классе
- переименовать одну из колонок полученного датасета в колонку "Сount"
- вывести значение "Сount" для пассажиров второго класса

In [69]:
#Решение#
import pandas as pd

path = "titanic.csv"
dataset = pd.read_csv(path)

dataset = dataset.rename(columns={'Survived': 'Count'})

print(dataset[['Pclass', 'Count']].groupby('Pclass').count())

dataset[(dataset.Pclass == 2)][['Count', 'Pclass']].groupby('Pclass').count()


        Count
Pclass       
1         216
2         184
3         487


Count
Pclass       
2         184

**+1 балл**

В последнем задании не хватает *посчитать сколько пассажиров в каждом классе*

Если добавите, то поставлю ещё балл